language: node_js
node_js:
  - '8'
env:
  global:
    # REGISTRY_TOKEN MesInfos
    - secure: aLlQvCviFJtXO4hFHLtdeHrxIo36rOqzoLgvm0qsW9NOMEp29B4aPYf4tx68wajxdQnCxO9xn68/6irOjV4/7zUoWHKwd7hbRopdk+sgtiO0b6xy/843BQoJ1laZ7oNnNzKH9zF4YrGF7NaXmLzY38yDOWbGrLajv+FhQhmBltAEIQtGsBjCwlFD1yG10JdQFKzgAKoxQM2/kLSZLxJFOIZGcMWxWYDx6RnuwEGA6aUO+nsmBIe1tqSx26XotqBBLGmk6j4gyJZFdeOvoHYKNZgdHyMlzVQ5SqUkp329ThXxCcFvYdaA/Sj4q3M49APBC4nT7PQ8ZK7AnoAZeelu8uw4MKtZKfoCB9/qxc2IWscd6JtMvxN/oNkzmCx70bPmQLsrmq75IESdPsd/jyKsJA8Sr4zN/7HhjmHHP6Z3iyU0GFFGYKWEKi26piKepMjXrovNgP5P9FiIVe5mX0J8McOrBMiktwl590CyAASOY2EQOa+Agzprwk+TzkZB9iUaUD/qR5dVc3FbtsreFx0N8yS8h7LPOrVpfFLFjwgKuGIfhS2czAH5wvEmFmQJWEElUSOHgFvvWC8CTftXgCktxjG6xaB/T38otr5hDEKmxywbNWgVFZK6GBktAkB9tXap+TOxRFeZqFKL5F6itMbqjK+SW1UfecPBBNqsYpDxJkg=
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
  - yarn lint
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build && yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build && yarn deploy && yarn cozyPublish
  on:
    tags: true
